const projectsInfos = [
  {
    title: "ON Target",
    imageUrl: "./onTarget-thumb.jpg",
    content: "descOnTarget",
    alt: "altOnTarget",
    githubLink: "https://github.com/MateusBorgesGuimaraes/on-target",
    youtubeLink: "https://youtu.be/_jJt2TWTgoU",
  },
  {
    title: "Factus Blog",
    imageUrl: "./factus-thumb.jpg",
    content: "descFactusBlog",
    alt: "altFactusBlog",
    githubLink: "https://github.com/MateusBorgesGuimaraes/factus-blog-app",
    youtubeLink: "https://youtu.be/NNFrB4Zxv8g",
  },
  {
    title: "Climb Up",
    imageUrl: "./climbUp-thumb.jpg",
    content: "descClimbUp",
    alt: "altClimbUp",
    githubLink: "https://github.com/MateusBorgesGuimaraes/climbUp",
    youtubeLink: "https://youtu.be/Wm4opcg7aiI",
  },
  {
    title: "For You",
    imageUrl: "./forYou-thumb.jpg",
    content: "descForYou",
    alt: "altForYou",
    githubLink: "https://github.com/MateusBorgesGuimaraes/for-you-app",
    youtubeLink: "https://youtu.be/l0mKvypCfyg",
  },
  {
    title: "Ocean Library",
    imageUrl: "./ocean-thumb.jpg",
    content: "descOcenaLibrary",
    alt: "altOcenaLibrary",
    githubLink: "https://github.com/MateusBorgesGuimaraes/ocean-library-app",
    youtubeLink: "https://youtu.be/tuUTBxXuOfs",
  },
  {
    title: "Reading Manager",
    imageUrl: "./readingManager-thumb.png",
    content: "descReadingManager",
    alt: "altReadingManager",
    githubLink: "https://github.com/MateusBorgesGuimaraes/Reading-Manager",
    youtubeLink: "https://youtu.be/7TCeOmc_UUI",
  },
  {
    title: "Feedbash ",
    imageUrl: "./feedbash-thumb.jpg",
    content: "descFeedbash",
    alt: "altFeedbash",
    githubLink: "https://github.com/MateusBorgesGuimaraes/feedbash",
    youtubeLink: "https://youtu.be/gWj-v3sbTuM",
  },
];

export default projectsInfos;
