const projectsInfos = [
  {
    title: "Paw.io",
    imageUrl: "./paw-io-thumb.jpg",
    content: "descPawio",
    alt: "altPawio",
    githubLink: "https://github.com/MateusBorgesGuimaraes/paw.io",
    youtubeLink: "https://youtu.be/Qc2rjcH-VBM",
  },
  {
    title: "Greep",
    imageUrl: "./greep-thumb.jpg",
    content: "descGreep",
    alt: "altGreep",
    githubLink: "https://github.com/MateusBorgesGuimaraes/grep",
    youtubeLink: "https://youtu.be/TwW0A-vbn7o",
  },
  {
    title: "Form Academy",
    imageUrl: "./form-academy-thumb.jpg",
    content: "descFormAcademy",
    alt: "altFormAcademy",
    githubLink: "https://github.com/MateusBorgesGuimaraes/form-academia",
    youtubeLink: "https://youtu.be/ATZTnefc6O4",
  },
  {
    title: "Mendes e associados",
    imageUrl: "./mendes-associados-thumb.jpg",
    content: "descMendesAssociados",
    alt: "altMendesAssociados",
    githubLink: "https://github.com/MateusBorgesGuimaraes/mendes-associados",
    youtubeLink: "https://youtu.be/0jX0u5YvX94",
  },
  {
    title: "ON Target",
    imageUrl: "./onTarget-thumb.jpg",
    content: "descOnTarget",
    alt: "altOnTarget",
    githubLink: "https://github.com/MateusBorgesGuimaraes/on-target",
    youtubeLink: "https://youtu.be/_jJt2TWTgoU",
  },
  {
    title: "Factus Blog",
    imageUrl: "./factus-thumb.jpg",
    content: "descFactusBlog",
    alt: "altFactusBlog",
    githubLink: "https://github.com/MateusBorgesGuimaraes/factus-blog-app",
    youtubeLink: "https://youtu.be/NNFrB4Zxv8g",
  },
  {
    title: "Climb Up",
    imageUrl: "./climbUp-thumb.jpg",
    content: "descClimbUp",
    alt: "altClimbUp",
    githubLink: "https://github.com/MateusBorgesGuimaraes/climbUp",
    youtubeLink: "https://youtu.be/Wm4opcg7aiI",
  },
  {
    title: "For You",
    imageUrl: "./forYou-thumb.jpg",
    content: "descForYou",
    alt: "altForYou",
    githubLink: "https://github.com/MateusBorgesGuimaraes/for-you-app",
    youtubeLink: "https://youtu.be/l0mKvypCfyg",
  },
  {
    title: "Ocean Library",
    imageUrl: "./ocean-thumb.jpg",
    content: "descOcenaLibrary",
    alt: "altOcenaLibrary",
    githubLink: "https://github.com/MateusBorgesGuimaraes/ocean-library-app",
    youtubeLink: "https://youtu.be/tuUTBxXuOfs",
  },
  {
    title: "Reading Manager",
    imageUrl: "./readingManager-thumb.png",
    content: "descReadingManager",
    alt: "altReadingManager",
    githubLink: "https://github.com/MateusBorgesGuimaraes/Reading-Manager",
    youtubeLink: "https://youtu.be/7TCeOmc_UUI",
  },
  {
    title: "Feedbash ",
    imageUrl: "./feedbash-thumb.jpg",
    content: "descFeedbash",
    alt: "altFeedbash",
    githubLink: "https://github.com/MateusBorgesGuimaraes/feedbash",
    youtubeLink: "https://youtu.be/gWj-v3sbTuM",
  },
];

export default projectsInfos;
